


###
GET http://localhost:3333/customers


###
POST http://localhost:3333/customer HTTP/1.1
Content-Type: application/json

{
  "name": "Luana",
  "email": "luh@test.com"
}

###
DELETE  http://localhost:3333/customer?65484c4c737841b0acdeba16